name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:15
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: escrow_mvp_ci
        ports:
          - 5432:5432
        options: >-
          --health-cmd "pg_isready -U postgres -d escrow_mvp_ci"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
      - name: Install dependencies
        run: npm ci
      - name: Wait for Postgres
        run: | 
          until pg_isready -h localhost -p 5432; do sleep 1; done
      - name: Set DATABASE_URL
        run: echo "DATABASE_URL=postgresql://postgres:postgres@localhost:5432/escrow_mvp_ci" >> $GITHUB_ENV
      - name: Prisma push
        run: npx prisma db push
      - name: Prisma generate
        run: npx prisma generate
      - name: Seed DB
        env:
          SEED_ADMIN_EMAIL: admin@escrow.co.ke
          SEED_ADMIN_PASSWORD: password123
        run: npx ts-node --transpile-only prisma/seed.ts
      - name: Run tests
        env:
          SESSION_SECRET: ci-secret
        run: npm test
